### ISSUE TITLE
ライトの円錐部分の光が出ません

### ISSUE THREAD

**Issue by taro-ww** [murasaqi/Unity_StageLightManeuver#29]
質問になります。

クイックスタート動画ではヒエラルキーにSLM_MovingBeamLight_URP_HDを入れただけで、ライトから出る光全てが描画されていましたが、こちらでやったところ光の円錐の部分が描画されていません。
「Volumetric Light Beam を利用することを推奨」と記載がありますが、利用しないと光の円錐部分は出ないということでしょうか？

![image](https://github.com/murasaqi/Unity_StageLightManeuver/assets/170487471/dd1cdcb2-f721-4b57-9db4-9c69b4c59744)

【環境】
unity 2022.3.9f1
URP
Volumetric Light Beamとの連携はしていません（未購入）

**Comment by AJpon** [comment]
名前に`VLB`と入っているプレハブは Volumetric Light Beam の設定がされたものになります  
未導入かつURPの場合は残念ながらボリューメトリックライト表現（光の円錐部分）はできません

HDRPの場合に限り、VLB未導入でも標準のボリューメトリックライト機能で代用ができます

**Comment by taro-ww** [comment]
ご回答ありがとうございます。
